# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fight Analytics 
email: contato@fightanalytics.cc
description: Fight Analytics - MMA Stats - UFC Statistics - Start engage all your MMA fans with a most effective product for your website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fightanalytics.cc" # the base hostname & protocol for your site
twitter_username: fightanalytics
github_username:  lucassanchez

# Build settings
markdown: kramdown
permalink: /:categories/:title/